<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>html.ep</string>
		<string>xml.ep</string>
	</array>
	<key>name</key>
	<string>Mojolicious Embedded Perl</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(%#(.+))$</string>
			<key>name</key>
			<string>comment.line.mojo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\&lt;%#(.+))\%&gt;</string>
			<key>name</key>
			<string>comment.line.mojo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\&lt;?%=) (javascript) (begin)\s*(%\&gt;)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.mojo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.mojo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.mojo</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.mojo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\&lt;?%) (end)\s*(%\&gt;)?</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.mojo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.mojo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.mojo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.mojo.block</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\&lt;?%=) (stylesheet) (begin)\s*(%\&gt;)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.mojo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.mojo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.mojo</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.mojo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\&lt;?%) (end)\s*(%\&gt;)?</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.mojo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.mojo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.mojo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.mojo.block</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\&lt;%={,2})</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.mojo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(=?%\&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.mojo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.mojo.embedded</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#mojo_support</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.perl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(%={,2})</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.mojo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>source.mojo.embedded.single</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#mojo_invalid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mojo_support</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.perl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>text.html.basic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>mojo_invalid</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>=?%\&gt;</string>
					<key>name</key>
					<string>invalid.punctuation.mojo</string>
				</dict>
			</array>
		</dict>
		<key>mojo_support</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string> \b(app|content|content_for|dumper|extends|flash|include|layout|memorize|param|session|stash|url_for|title|base_tag|check_box|file_field|form_for|hidden_field|input_tag|javascript|link_to|password_field|radio_button|select_field|stylesheet|submit_button|tag|text_area|text_field)\b </string>
					<key>name</key>
					<string>support.function.mojo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(begin|end)\b</string>
					<key>name</key>
					<string>entity.name.function.mojo</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mojo.html</string>
	<key>uuid</key>
	<string>dde3a46b-24e2-4bfd-b911-b86ba73489ba</string>
</dict>
</plist>
